name: ygo_vision
description: "Gestion de collection YuGiOh + reconnaissance de carte"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.3.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  fluttertoast: ^8.2.12
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/cards.png
    - assets/img/collection.png
    - assets/img/deck.png
    - assets/img/scan.png

  fonts:
    # Pour les titres
    - family: Card Name
      fonts:
        - asset: fonts/Yu-Gi-Oh! Matrix Regular Small Caps 2.ttf
    # Pour les effets de cartes
    - family: Card Effect
      fonts:
        - asset: fonts/Yu-Gi-Oh! Matrix Book.ttf
    # Pour les monstres sans effets
    - family: No Effect Monsters
      fonts:
        - asset: fonts/Yu-Gi-Oh! ITC Stone Serif LT Italic.ttf
    # Pour les types de monstres, magies ou pièges
    - family: Card Type
      fonts:
        - asset: fonts/Yu-Gi-Oh! ITC Stone Serif Small Caps Bold.ttf