// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhiS0fHVvNQIryzraYJk4d2n0yWLb8Og',
    appId: '1:558093047124:web:a1046135e4a47e508f64c1',
    messagingSenderId: '558093047124',
    projectId: 'ygo-vision',
    authDomain: 'ygo-vision.firebaseapp.com',
    storageBucket: 'ygo-vision.firebasestorage.app',
    measurementId: 'G-X26RGRMBHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl37j-4kc42weefZG-MjnpOxuq8u64QM4',
    appId: '1:558093047124:android:01575f7003556ff78f64c1',
    messagingSenderId: '558093047124',
    projectId: 'ygo-vision',
    storageBucket: 'ygo-vision.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMhiS0fHVvNQIryzraYJk4d2n0yWLb8Og',
    appId: '1:558093047124:web:e226377c74753bc08f64c1',
    messagingSenderId: '558093047124',
    projectId: 'ygo-vision',
    authDomain: 'ygo-vision.firebaseapp.com',
    storageBucket: 'ygo-vision.firebasestorage.app',
    measurementId: 'G-CQJGL4LKBS',
  );
}
